import {DEFAULT_RATE_LIMIT_POLICY,SPECIALIST_AGENTS} from './policies.mjs';
const utcDate=(d=new Date())=>d.toISOString().slice(0,10);
export class QuotaError extends Error { constructor(limit,current,maximum,now=new Date()){super(`Quota reached: ${limit}`);this.code='QUOTA_EXCEEDED';this.details={limit,current,maximum,resetTime:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+1)).toISOString(),availableNonAiActions:['View pantry','Edit confirmed quantity','Read saved shopping list'],hasAdminException:false};} }
export class QuotaEngine {
 constructor(store,policy=DEFAULT_RATE_LIMIT_POLICY){this.store=store;this.policy=policy;}
 async reserve(input){
  if(!SPECIALIST_AGENTS.includes(input.agent))throw Error('Unknown specialist agent');
  if(!input.idempotencyKey||!input.uid||!input.sessionId)throw Error('Missing quota identity');
  if((input.recursiveDepth||0)>this.policy.recursiveSteps)throw new QuotaError('recursiveSteps',input.recursiveDepth,this.policy.recursiveSteps,input.now);
  if(input.modality==='live'&&(input.requestedSeconds||0)>this.policy.maxLiveSeconds)throw new QuotaError('maxLiveSeconds',input.requestedSeconds,this.policy.maxLiveSeconds,input.now);
  if((input.videoSeconds||0)>this.policy.maxVideoSeconds)throw new QuotaError('maxVideoSeconds',input.videoSeconds,this.policy.maxVideoSeconds,input.now);
  if((input.images||0)>this.policy.imagesPerEvaluation)throw new QuotaError('imagesPerEvaluation',input.images,this.policy.imagesPerEvaluation,input.now);
  if((input.uploadBytes||0)>this.policy.maxUploadBytes)throw new QuotaError('maxUploadBytes',input.uploadBytes,this.policy.maxUploadBytes,input.now);
  if((input.receiptPages||0)>this.policy.receiptPages)throw new QuotaError('receiptPages',input.receiptPages,this.policy.receiptPages,input.now);
  if((input.voiceSeconds||0)>this.policy.maxVoiceClipSeconds)throw new QuotaError('maxVoiceClipSeconds',input.voiceSeconds,this.policy.maxVoiceClipSeconds,input.now);
  return this.store.transaction(async tx=>{const key=`${input.uid}:${utcDate(input.now)}:${input.idempotencyKey}`;const existing=tx.getReservation(key);if(existing)return existing;if(this.policy.killSwitch||tx.isDisabled(input.agent,input.model))throw new QuotaError('emergencyKillSwitch',1,0,input.now);const bucket=tx.getBucket(input.uid,utcDate(input.now));const agentCount=bucket.sessionsByAgent[input.agent]||0;if(input.startsSession&&agentCount>=this.policy.sessionsPerAgentPerUtcDay)throw new QuotaError('sessionsPerAgentPerUtcDay',agentCount,this.policy.sessionsPerAgentPerUtcDay,input.now);if(bucket.billableInvocations>=this.policy.totalBillableInvocationsPerUtcDay)throw new QuotaError('totalBillableInvocationsPerUtcDay',bucket.billableInvocations,this.policy.totalBillableInvocationsPerUtcDay,input.now);if(input.modality==='live'&&bucket.liveSessions>=this.policy.liveSessionsPerUtcDay)throw new QuotaError('liveSessionsPerUtcDay',bucket.liveSessions,this.policy.liveSessionsPerUtcDay,input.now);if(input.modality==='image'&&bucket.images+(input.images||1)>this.policy.imagesPerUtcDay)throw new QuotaError('imagesPerUtcDay',bucket.images,this.policy.imagesPerUtcDay,input.now);if(tx.active(input.uid,input.modality)>=(input.modality==='live'?this.policy.concurrentLiveSessions:this.policy.concurrentStaticRequests))throw new QuotaError('concurrentRequests',tx.active(input.uid,input.modality),input.modality==='live'?this.policy.concurrentLiveSessions:this.policy.concurrentStaticRequests,input.now);const reservation={...input,key,status:'reserved',policyVersion:this.policy.version,createdAt:(input.now||new Date()).toISOString()};tx.reserve(reservation);return reservation;});
 }
 async reconcile(key,usage){return this.store.transaction(async tx=>{const r=tx.getReservation(key);if(!r)throw Error('Reservation not found');if(r.status==='finalized')return r;tx.finalize(key,usage);return tx.getReservation(key);});}
}
export class MemoryQuotaStore {constructor(){this.buckets=new Map();this.reservations=new Map();this.disabled=new Set();this.queue=Promise.resolve();}transaction(fn){const next=this.queue.then(()=>fn(this));this.queue=next.catch(()=>{});return next;}getReservation(k){return this.reservations.get(k);}getBucket(uid,date){const k=`${uid}:${date}`;if(!this.buckets.has(k))this.buckets.set(k,{sessionsByAgent:{},billableInvocations:0,liveSessions:0,images:0});return this.buckets.get(k);}isDisabled(agent,model){return this.disabled.has(agent)||this.disabled.has(model);}active(uid,modality){return [...this.reservations.values()].filter(r=>r.uid===uid&&r.modality===modality&&r.status==='reserved').length;}reserve(r){this.reservations.set(r.key,r);}finalize(k,u){const r=this.reservations.get(k);const b=this.getBucket(r.uid,utcDate(r.now));r.status='finalized';r.usage={...u};r.success=!!u.success;r.billed=!!u.billed;if(u.billed){b.billableInvocations++;if(r.startsSession)b.sessionsByAgent[r.agent]=(b.sessionsByAgent[r.agent]||0)+1;if(r.modality==='live')b.liveSessions++;b.images+=u.images||0;}}}
